require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'FantuanDemo' do
  
  pod 'SDWebImage', '~> 5.0'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'FantuanImage', :git => 'https://develop.dianpings.com/gitlab/frontend/fantuanimage.git',:modular_headers => true
#  pod 'FantuanImage', :path => '/Users/ricky/Desktop/Fantuan/FantuanImage', :modular_headers => true
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'FantuanDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

 post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)
  end
end
