require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'FantuanDemo' do
  
  pod 'SDWebImage', '~> 5.0'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'FantuanImage', :git => 'http://website.nerdlinux.com:8093/frontend/ios-components/fantuanimage.git',:modular_headers => true
#  pod 'FantuanImage', :path => '/Users/ricky/Desktop/Fantuan/FantuanImage', :modular_headers => true
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  


  target 'FantuanDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
